# Generated by Django 4.2 on 2024-05-13 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AymaraAPP', '0002_metodo_pago_usuario_producto_pedido_carrito'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCarrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='ProductoEnCarrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('item_carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AymaraAPP.itemcarrito')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AymaraAPP.producto')),
            ],
        ),
        migrations.AddField(
            model_name='itemcarrito',
            name='productos',
            field=models.ManyToManyField(through='AymaraAPP.ProductoEnCarrito', to='AymaraAPP.producto'),
        ),
    ]
